const MAIN_CATEGORY_INDICATOR_HEIGHT = 6;

export const heights = {
  TOP_BANNER_HEIGHT: 170,
  WALLET_HEIGHT: 78,
  NAVIGATION_HEADER_HEIGHT: 51,
  WALLET_OFFSET: -10,
  MAIN_CATEGORY_HEIGHT: 170 + MAIN_CATEGORY_INDICATOR_HEIGHT,
  MAIN_CATEGORY_INDICATOR_HEIGHT: MAIN_CATEGORY_INDICATOR_HEIGHT,
};
